name: video_player_task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.6.0

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    flutter_bloc: ^8.1.0
    chewie: ^1.7.0
    video_player: ^2.8.1
    path_provider: ^2.1.5
    flutter_downloader: ^1.12.0
    permission_handler: ^12.0.0+1
    http: ^0.13.5
    connectivity_plus: ^6.1.4
    flutter_cache_manager: ^3.3.1
    dio: ^5.8.0+1
    shared_preferences: ^2.5.3
    equatable: ^2.0.7
    # video_thumbnail: ^0.5.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
